baseURL = "/"
languageCode = "en-au"
title = "Leon Seng"
theme = "cactus"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 20

  [[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 30

  [[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 40

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 50

[params]
  colortheme = "dark"
  css = ["css/custom.css"]
  description = """
  I glue tools together in the hidden world of network infrastructure automation.

  And this is where I get things off my mind!
  """
  mainSection = "posts"
  mainSectionTitle = "Latest posts"
  tocInline = true

  [[params.social]]
    name = "github"
    link = "https://github.com/leonseng"

  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/leonseng/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
