baseURL = "https://leonseng.netlify.app/"
languageCode = "en-au"
title = "Leon Seng"
theme = "cactus"

[params]
  colortheme = "dark"
  css = ["css/custom.css"]
  description = """
  I glue tools together in the hidden world of network infrastructure automation.

  And this is where I get things off my mind!
  """
  mainSection = "posts"
  mainSectionTitle = "Latest posts"

  [[params.social]]
    name = "github"
    link = "https://github.com/leonseng"

  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/leonseng/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 2

  [[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 3

  [[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 5
